export const AppConfig = {
  parkName: "PortAventura World",
  headerTitle: "Skip the Wait at PortAventura World",
  headerSubtitle: "Average Wait Times",
  backButton: {
    enabled: true,
    label: "Back",
    targetUrl: "https://park-wait-radar.lovable.app",
    openInNewTab: false,
  },
  animation: {
    flipDuration: 0.6,
    hoverScale: 1.03,
  },
  requiredColumns: ["timestamp", "ride_name", "wait_time", "availability"] as const,
};

export const rideDescriptions: Record<string, string> = {
  "Bumper Cars": "Drive small cars and bump into others in a fun arena.",
  "Bungee Jump": "Jump from a high platform with a safety harness for a big thrill.",
  "Circus Train": "Gentle family train ride through circus-themed scenes.",
  "Crazy Dance": "Spinning ride that lifts and tilts you while music plays.",
  "Dizzy Dropper": "Small ride with short drops and spinning motion.",
  "Drop Tower": "Tall tower ride with a sudden vertical free fall.",
  "Flying Coaster": "High-speed coaster where riders lie face-down.",
  "Free Fall": "Compact drop ride with fast, repeated falling sensations.",
  "Giant Wheel": "Ferris wheel with slow panoramic views of the park.",
  "Giga Coaster": "Very tall and fast roller coaster with big drops.",
  "Go-Karts": "Drive small racing cars around a track.",
  "Haunted House": "Dark ride with spooky rooms and surprise effects.",
  "Himalaya Ride": "Classic fairground ride with fast spins and music.",
  "Inverted Coaster": "Roller coaster with seats hanging below the track.",
  "Kiddie Coaster": "Small roller coaster designed for young riders.",
  "Merry Go Round": "Traditional carousel with gentle up-and-down motion.",
  "Oz Theatre": "Indoor theatre show with themed visuals and effects.",
  "Rapids Ride": "River rapids ride with spinning rafts and splashes.",
  "Roller Coaster": "Traditional coaster with turns, dips, and speed.",
  "Spinning Coaster": "Roller coaster where the cars spin as you ride.",
  "Spiral Slide": "Tall slide that spirals down in a long curve.",
  "Superman Ride": "High-speed launch ride with strong acceleration.",
  "Swing Ride": "Chairs swing high in the air while spinning around.",
  "Vertical Drop": "Ride that lifts you up before dropping straight down.",
  "Water Ride": "Boat ride with splashes and small drops.",
  "Zipline": "Glide across the park on a suspended cable.",
};
